all: scrabble	

scrabble: Game_Design.cpp Move.cpp ConsolePrinter.cpp Player.cpp scrabble.cpp Bag.cpp Dictionary.cpp Board.cpp CPUL.cpp Trie.cpp CPUS.cpp CPU.cpp
	g++ -g -Wall -std=c++11 Game_Design.cpp Move.cpp ConsolePrinter.cpp Player.cpp scrabble.cpp Bag.cpp Dictionary.cpp Board.cpp CPUL.cpp Trie.cpp CPU.cpp CPUS.cpp -o scrabble
	